help/urls.py
from django.conf.urls import patterns, url

from help import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ehfHelp/$',views.ehfHelp,name='ehfHelp'),
    url(r'^searchHelp/$', views.searchHelp, name='searchHelp'),
    url(r'^browseHelp/$', views.browseHelp, name='browseHelp'),
    url(r'^analysisHelp/$', views.analysisHelp, name='analysisHelp'),
    url(r'^restHelp/$', views.restHelp, name='restHelp'),
    url(r'^citeHelp/$', views.citeHelp, name='citeHelp'),
)

smuggler/urls.py
# Copyright (c) 2009 Guilherme Gondim and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.

try:
    from django.conf.urls import url, patterns
except ImportError:  # Django < 1.4
    from django.conf.urls.defaults import url, patterns
                            
from smuggler.views import (dump_data, dump_app_data, dump_model_data,
                            load_data)

dump_data_url = url(
    regex=r'^dump/$',
    view=dump_data,
    name='dump-data'
)

dump_app_data_url = url(
    regex=r'^(?P<app_label>\w+)/dump/$',
    view=dump_app_data,
    name='dump-app-data'
)

dump_model_data_url = url(
    regex=r'^(?P<app_label>\w+)/(?P<model_label>\w+)/dump/$',
    view=dump_model_data,
    name='dump-model-data'
)

load_data_url = url(
    regex=r'^load/$',
    view=load_data,
    name='load-data'
)

urlpatterns = patterns('', dump_model_data_url, dump_app_data_url,
                       dump_data_url, load_data_url)

tools/urls.py
from django.conf.urls import patterns, url
from tools import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^snp/download/$', views.snpDownload, name='snpDownload'),
    url(r'^snp/$', views.snp, name='snp'),
    url(r'^snpResult/$', views.snpResult, name='snpResult'),
    url(r'^snpView/(?P<id>[\w]+)/$', views.snpView, name='snpView'),
    url(r'^intergenic/$', views.intergenic, name='intergenic'),
    url(r'^intergenicResult/$', views.intergenicResult, name='intergenicResult'),
    url(r'^intergenic/download/$', views.intergenicDownload, name='intergenicDownload'),
    url(r'^intergenicView/(?P<id>[\w |\-_:]+)/$', views.intergenicView, name='intergenicView'),

    url(r'^homology/download/$', views.homologyDownload, name='homologyDownload'),
    url(r'^homology/$', views.homology, name='homology'),
    url(r'^homologyResult/$', views.homologyResult, name='homologyResult'),
    url(r'^homologyView/$', views.homologyView, name='homologyView'),
    url(r'^homologyViewNetwork/$', views.homologyViewNetwork, name='homologyViewNetwork'),
    url(r'^blastIndex/$', views.blastIndex, name='blastIndex'),
    url(r'^blast/$', views.blast, name='blast'),
    url(r'^blastResult/$', views.blastResult, name='blastResult'),
    url(r'^ajaxQueryState/$', views.ajaxQueryState, name='ajaxQueryState'),
)

ypga/urls.py
from django.conf.urls import patterns, include, url
from settings import *
from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ehf.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': MEDIA_ROOT, 'show_indexes': True}),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/images/favicon.ico'}),
    url(r'^$', 'ypga.views.index'),
    url(r'^versionUpdate/$', 'ypga.views.versionUpdate'),

    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^download/', include('download.urls', namespace="download")),
    url(r'^about/', include('about.urls', namespace="about")),
    url(r'^tools/', include('tools.urls', namespace="tools")),
    url(r'^help/', include('help.urls', namespace="help")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

blast/models.py
from django.db import models

# Create your models here.

tools/models.py
from django.db import models
from formatChecker import ContentTypeRestrictedFileField

# DATABASE_CHOICES = (
#          ('genome','All Genome Sequences'),
#          ('gene','All Gene Sequences'),
#          ('protein','All Protein Sequences'),
#          ('draft','All Draft Sequences'),
# )
#
# ALIGNMENTS_CHOICES = (
#          ('10','10'),
#          ('50','50'),
#          ('100','100'),
#          ('250','250'),
#          ('500','500'),
#          ('1000','1000'),
#
# )
#
# EXPECT_CHOICES = (
#          ('0.0001','0.0001'),
#          ('0.01','0.001'),
#          ('1','1'),
#          ('10','10'),
#          ('100','100'),
#          ('1000','1000'),
# )
#
# MATRIX_CHOICES = (
#          ('PAM30','PAM30'),
#          ('PAM70','PAM70'),
#          ('BLOSUM80','BLOSUM80'),
#          ('BLOSUM62','BLOSUM62'),
#          ('BLOSUM45','BLOSUM45'),
# )

# Create your models here.
class blastModel(models.Model):
    querySeq = models.TextField(blank=True)
    queryFile = ContentTypeRestrictedFileField(upload_to='blast/queryFiles/', content_types=['text/plain',''],max_upload_size=1048576*20,blank=True, null=True)
    # database = models.CharField(max_length=20,choices=DATABASE_CHOICES)
    # alignments = models.CharField(max_length=20,choices=ALIGNMENTS_CHOICES)
    # expect = models.CharField(max_length=20,choices=EXPECT_CHOICES)
    # matrix = models.CharField(max_length=20,choices=MATRIX_CHOICES)
    # filterQuery = models.CharField(max_length=20)

class blastResultModel(models.Model):
    jobId = models.CharField(primary_key=True,max_length=40)
    status = models.CharField(max_length=20)  #status
    resultFile = models.CharField(max_length=255)  #result file path

tools/forms.py
from django.forms import ModelForm,Textarea
from tools.models import blastModel

class blastForm(ModelForm):
    class Meta:
        model = blastModel
        widgets = {
            'querySeq': Textarea(attrs={'cols': 80, 'rows': 8}),
        }

blast/views.py
from django_gearman import GearmanClient
from tools.views import blastResultModel

#called from the tools view
def callBlast(queryFile, database, resultFile, num_alignments, num_descriptions, expect,max_target_seqs,jobId):

    client = GearmanClient()
    result = client.submit_job("runBlast",background=True,
                              kwargs={"queryFile": queryFile, "database": database, "resultFile": resultFile,
                                      "num_alignments": num_alignments,"num_descriptions":num_descriptions,
                                      "expect":expect,'max_target_seqs':max_target_seqs,'jobId':jobId})

    print result.state
    # record the job id in the model blastresult
    job = blastResultModel(jobId=jobId,status=result.state,resultFile=resultFile)
    job.save()
    print result

tools/views.py
import csv
import random
import time
import json

from django.shortcuts import render_to_response
from django.shortcuts import HttpResponseRedirect
from django.db.models import Q
from django.template import RequestContext
from django.http import HttpResponse
from django.utils.encoding import smart_str
from django.http import HttpResponse

from browse.models import *
from browse.commonVar import *
from ypga.settings import PKL_DIR
from tools.forms import blastForm
from ypga.settings import BLAST_DIR
from tools.models import *

#pkl
import os
import cPickle as pickle
import hashlib

#gearman
from blast.views import callBlast

from collections import defaultdict

# Create your views here.
def index(request):
    return render_to_response('tools/index.html')


def snp(request):
    return render_to_response('tools/snp.html', {'strainDic': strainDic})


def snpDownload(request):
    if request.method == 'POST':
        if 'selected[]' in request.POST:
            selected = request.POST.getlist('selected[]')

            result = Snp.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=snp.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in snpField:
                rowTitle.append(snpFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in snpField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/tools/snp/')


#given a string, return the list
def getList(geneListTmp):
    geneList = []
    if ',' in geneListTmp:
        geneList = geneListTmp.split(',')
    elif '\n' in geneListTmp:
        geneList = geneListTmp.split('\n')
    elif '\r\n' in geneListTmp:
        geneList = geneListTmp.split('\r\n')
    elif ';' in geneListTmp:
        geneList = geneListTmp.split(';')
    else:
        geneList.append(geneListTmp)
    result = []
    for item in geneList:
        result.append(item.strip())

    return result


#get type
# def getType(item):
#     if 'ref' in item:
#         type = 'id'
#     else:
#         type = 'locus'
#     return type


#get strain list
def getStrainAndId(geneList):
    q = Q(id__in=geneList) | Q(locus__in=geneList)
    result = NcbiGene.objects.filter(q)

    strainList = []
    strain = result.values_list('strain').distinct()
    for item in strain:
        strainList.append(item[0])

    idList = []
    id = result.values_list('id').distinct()
    for item in id:
        idList.append(item[0])

    return strainList, idList


def snpResult(request):
    if request.method == 'GET':
        if 'geneList' in request.GET:
            geneListTmp = request.GET['geneList'].strip()

            #get strain list for filter
            strainList1 = []
            idList1 = []
            if len(geneListTmp):
                geneList = getList(geneListTmp)
                strainList1, idList1 = getStrainAndId(geneList)

            strainList2 = []
            if 'strain' in request.GET:
                strainList2 = request.GET.getlist('strain')
            strainList = list(set(strainList1) | set(strainList2))

            idList2 = []
            if len(strainList2):
                #pkl
                name = '-'.join(strainList2)
                name = 'snp-' + hashlib.md5(name).hexdigest()

                if os.path.isfile(PKL_DIR + '/' + name + '.pkl'):  #have pickle
                    file_out = file(PKL_DIR + '/' + name + '.pkl', 'rb')
                    idList2 = pickle.load(file_out)
                    file_out.close()
                else:
                    tmp = NcbiGene.objects.filter(strain__in=strainList2).values_list('id').distinct()
                    for item in tmp:
                        idList2.append(item[0])

                    #generate pickle
                    file_snp = file(PKL_DIR + '/' + name + '.pkl', 'wb')
                    pickle.dump(idList2, file_snp, True)
                    file_snp.close()

            idList = list(set(idList1) | set(idList2))

            type = request.GET['type']
            if type == 'snp':

                result = Snp.objects.filter(id1__in=idList)

                strainSelected = ','.join(strainList)
                strainSelectedNumber = len(strainList)

                #if column in the url, we filter the result
                # too complicated, add strain in gene or snp table
                if 'columns' in request.GET:
                    columns = request.GET['columns']
                    if len(columns.strip()) > 0:
                        columns = columns.split(',')
                        strainSelected = ','.join(columns)
                        strainSelectedNumber = len(columns)
                        # tmp = NcbiGene.objects.filter(strain__in=columns).values_list('id').distinct()
                        # idFilter = []
                        # for item in tmp:
                        #     idFilter.append(item[0])
                        result = result.filter(strain__in=columns)

                if (len(result)):
                    #sort the column
                    order = request.GET.get('order_by', 'id')
                    result = result.order_by(order)

                interactions = len(result)

                strainToDic = {}
                for item in strainList:
                    strainToDic[item] = strainDic[item]

                #ids for download
                ids = []
                idTmp = result.values_list('id')
                for item in idTmp:
                    ids.append(str(item[0]))

                return render_to_response('tools/snpResult.html',
                                          {'result': result, 'strain': strainToDic, 'strainSelected': strainSelected,
                                           'strainSelectedNumber': strainSelectedNumber, 'interactions': interactions,
                                           'ids': ','.join(ids)},
                                          context_instance=RequestContext(request))
            else:  #allele
                q = Q(id1__in=idList) & Q(id2__in=idList)
                result = Snp.objects.filter(q)

                if (len(result)):
                    #sort the column
                    order = request.GET.get('order_by', 'id')
                    result = result.order_by(order)

                interactions = len(result)

                #ids for download
                ids = []
                idTmp = result.values_list('id')
                for item in idTmp:
                    ids.append(str(item[0]))

                return render_to_response('tools/snpIntraResult.html',
                                          {'result': result, 'interactions': interactions, 'ids': ','.join(ids)},
                                          context_instance=RequestContext(request))

    return HttpResponseRedirect('/')


def snpView(request, id):
    result = Snp.objects.filter(id=id)[0]
    snpposlist = result.snpposlist.split(';')

    if '' in snpposlist:
        snpposlist.remove('')

    print snpposlist
    seq1 = NcbiGene.objects.filter(id=result.id1)[0].seq
    seq2 = NcbiGene.objects.filter(id=result.id2)[0].seq
    alignments = generateAlign(snpposlist, seq1, seq2)

    #generate snp allele
    allele1 = SnpAllele.objects.filter(id=result.id1)[0].allelelist
    allele2 = SnpAllele.objects.filter(id=result.id2)[0].allelelist
    posDict1= defaultdict()
    posDict2 = defaultdict()
    allele1List =  allele1.split(';')
    if '' in allele1List:
        allele1List.remove('')

    allele2List =  allele2.split(';')
    if '' in allele2List:
        allele2List.remove('')

    for item in allele1List:
        pos = int(item[0:item.index('_')])
        chars = item[item.index('_')+1:]
        posDict1[pos] = chars

    for item in allele2List:
        pos = int(item[0:item.index('_')])
        chars = item[item.index('_')+1:]
        posDict2[pos] = chars

    commonPos = set(posDict1.keys()) & set(posDict2.keys())
    allele1Dict = {}
    allele2Dict = {}
    posList = []
    for item in commonPos:
        posList.append(item)
        allele1Dict[item] = posDict1[item]
        allele2Dict[item] = posDict2[item]

    posList.sort()

    return render_to_response('tools/snpView.html', {'id': id, 'result': result, 'alignments': alignments,'posList':posList,'allele1Dict':allele1Dict,'allele2Dict':allele1Dict})


#given a snppos and related seq, return the aligned result
def generateAlign(snpposlist, seq1, seq2):
    pos1List = []
    pos2List = []
    char1List = []
    char2List = []
    for item in snpposlist:
        pos = item.split(':')
        pos1List.append(pos[0].split('_')[0])
        char1List.append(pos[0].split('_')[1])
        pos2List.append(pos[1].split('_')[0])
        char2List.append(pos[1].split('_')[1])
    alignments1 = ''
    alignments_middle = ''
    alignments2 = ''

    for i in range(0, len(pos1List)):
        alignments1 = alignments1 + char1List[i]
        alignments_middle = alignments_middle + '|'
        alignments2 = alignments2 + char2List[i]
        #append five char before and after

        #more than two
        if len(pos1List) > 1:

            if i == 0:  #first one
                #left for pos1List and middle
                if int(pos1List[i]) > 4:
                    alignments1 = seq1[int(pos1List[i]) - 6:int(pos1List[i]) - 1] + alignments1

tools/templates/tools/blastIndex.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>
{#    <script src='/static/jquery.clearsearch.js'></script>#}
    <script src='/static/tools/blast.js'></script>

    <div class="main">
        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'tools:index' %}">Tools</a></li>
            <li class="active">BLAST Index</li>
        </ol>

        <div class="blastIndex">
            <div class="blastTitle">
                Query JOB
            </div>
            <div class="blastContent">
                <div style="margin-bottom: 10px">Input the job id given when the job is submitted.</div>

                <form action="/tools/blastResult" method="get" role="form">
                    <input name="jobId" class="query" id="focusedInput" type="text" placeholder="search job">
                    <button type="submit" class="btn btn-default btn-sm"><span
                            class="glyphicon glyphicon-search"></span>
                        Search
                    </button>
                </form>
            </div>

            <div class="blastTitle">
                Submit JOB
            </div>
            <div class="blastContent">
                You can submit your blast job <a href="{% url 'tools:blast' %}">here</a>.
            </div>
        </div>
    </div>
{% endblock %}

tools/templates/tools/blastResult.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>
    <script src='/static/tools/blastResult.js'></script>

    <div class="main">
        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'tools:index' %}">Tools</a></li>
            <li class="active">BLAST Result</li>
        </ol>

        <div class="blastIndex">
            Your job has been submitted. The computation time may be variable based on the server load.
            <div class="jobId">
                <b>JOB ID:</b>
                <span id="jobId">{{ jobId }}</span>
            </div>
            <p>You can close this page and query your result with the <b>JOB ID</b> later.</p>

            <div id="loading">
                <img src="/static/tools/images/loading6.gif">
            </div>


        </div>
    </div>
{% endblock %}

tools/templates/tools/homologyViewOthers.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tools/infovis/ForceDirected.css' %}"/>
    <!--[if IE]><script src='/static/analysis/infovis/excanvas.js'></script><![endif]-->
    <script src='/static/tools/infovis/jit.js'></script>
    <script src='/static/tools/infovis/network.js'></script>
    <script src='/static/csrf.js'></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js'></script>

    <div class="main" style="background-color: #FDFDFD" id="main">

        <div id="geneList" style="display:none">{{ geneList }}</div>

        <div class="toolsMain">
            <div id="otherLoading">
                <img src="/static/tools/images/loading6.gif"/>
            </div>
        </div>

    </div>

    <script type="text/javascript" language="JavaScript">
        $(document).ready(function () {
            var text = $('#geneList').text();
            //change to ajax post to avoid too long url
            $.post("/tools/homologyViewNetwork/", {'text': text, csrfmiddlewaretoken: '{{csrfmiddlewaretoken}}'}, evalCallbk);  //get search types from server
        });
    </script>

{% endblock %}

tools/templates/tools/index.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>

    <div class="main">
        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li class="active">Tools</li>
        </ol>

        <div class="toolsIndex">

            <div style="margin-top: 20px;font-size: 18px;font-weight: bold">Diversity Analysis Tools</div>
            <div class="analysisType">
                <a href="{% url 'tools:snp' %}">SNP Analysis</a>
            </div>
            <div class="analysisDes">
                <ul>
                    <li>
                        SNP analysis
                    </li>
                </ul>
            </div>

            <div style="margin-top: 20px;font-size: 18px;font-weight: bold">Homology Analysis Tools</div>
            <div class="analysisType">
                <a href="{% url 'tools:intergenic' %}">Intergenic Analysis</a>
            </div>
            <div class="analysisDes">
                <ul>
                    <li>
                        Intergenic analysis
                    </li>
                </ul>
            </div>

            <div class="analysisType">
                <a href="{% url 'tools:homology' %}">Homology Analysis</a>
            </div>
            <div class="analysisDes">
                <ul>
                    <li>
                        Homology analysis
                    </li>
                </ul>
            </div>

            <div class="analysisType">
                <a href="{% url 'tools:blastIndex' %}">BLAST Analysis</a>
            </div>
            <div class="analysisDes">
                <ul>
                    <li>
                        BLAST analysis
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

tools/templates/tools/intergenicView.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>
    <script src="/static/tools/scribl/Scribl.1.1.3.min.js"></script>
    <script src="/static/tools/intergenicView.js"></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'tools:index' %}">Tools</a></li>
            <li><a href="{% url 'tools:snp' %}">Intergenic Analysis</a></li>
            <li class="active">View</li>
        </ol>

        <div class="toolsMain">
            Intergenic result for <span id="idintergenic">{{ result.idintergenic }}</span>.<br/>

            <div id="idDes">
                <label>upstreamgeneid:</label>
                <span id="upstreamgeneid">{{ result.upstreamgeneid }}</span>
            </div>
            <div id="idDes">
                <label>downstreamgeneid:</label>
                <span id="downstreamgeneid">{{ result.downstreamgeneid }}</span>
            </div>

            <div id="idDes2"><label>View of Intergenic:</label></div>

            <div id="container">
                <canvas id="canvas"></canvas>
                </br><a id="export">Export as PNG (right click Save As)</a>
            </div>

        </div>

    </div>

{% endblock %}

tools/templates/tools/queryBlastResult.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>

    <div class="main">
        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'tools:index' %}">Tools</a></li>
            <li class="active">BLAST Result</li>
        </ol>

        <div class="blastIndex">
            <div class="jobId">
                <b>JOB ID:</b>
                <span id="jobId">{{ jobId }}</span>
            </div>

            <div class="msg">
                {{ msg | safe }}
            </div>


        </div>
    </div>
{% endblock %}

tools/templates/tools/snpIntraResult.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Tools</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'tools/tools.css' %}"/>
    <script src="/static/tools/snp.js"></script>
    <script src='/static/browse/jquery.fileDownload.js'></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'tools:index' %}">Tools</a></li>
            <li><a href="{% url 'tools:snp' %}">SNP Analysis</a></li>
            <li class="active">Result</li>
        </ol>

        <div class="toolsMain">

            <div id="geneSummary">Summary: Query contains <span
                    id="interactions">{{ interactions }}</span> interaction{{ interactions|pluralize}}.
            </div>
            <div id="functionDiv" class="functionDiv">
                <div id="selectHint" class="selectHint">
                    <b><span id="selectNumber">0</span></b> items selected
                </div>
                <input type="checkbox" id="selectAllPage" value="selectAllPage" onclick="selectAllPage(this);">
                <label id="selectAllPage"> Select all records </label>

                        <span id="buttonGroup">
                            <button id="downloadFunc" class="btn btn-primary btn-sm"
                                    onclick="performFunction('download');">Download
                            </button>

                        </span>
                        <span id="geneDownloadTip"><a href="{% url 'help:browseHelp' %}#snp" target="_blank"><img
                                src="/static/images/info_20x20.png"></a></span>

            </div>
            <div id="preparing-file-modal" title="Preparing report..." style="display: none;">
                We are preparing your file, please wait...

                <div class="ui-progressbar-value ui-corner-left ui-corner-right"
                     style="width: 100%; height:22px; margin-top: 20px;"></div>
            </div>

            <div id="error-modal" title="Error" style="display: none;">
                There was a problem generating your file, please try again.
            </div>

            <span id="ids" style="display:none">{{ ids }}</span>

            <div id="csrf" style="display:none" value="{% csrf_token %}"></div>

            {% if result %}
                <table class="table table-hover table-striped table-bordered table-condensed" id="geneTable">
                    <thead>
                    <tr class="tableHead">
                        <th id="tableSelectAll">
                            <input type="checkbox" id="selectCurrentPage" value="selectCurrentPage"
                                   onclick="selectCurrentPage(this)">
                        </th>
                        <th name="id"><a href="?{% url_replace request 'order_by' 'id' %}">ID</a></th>
                        <th name="id1"><a href="?{% url_replace request 'order_by' 'id1' %}">id1</a></th>
                        <th name="strain1"><a href="?{% url_replace request 'order_by' 'strain1' %}">strain1</a></th>
                        <th name="id2"><a href="?{% url_replace request 'order_by' 'id2' %}">id2</a>
                        <th name="strain2"><a href="?{% url_replace request 'order_by' 'strain2' %}">strain2</a></th>
                        </th>
                        <th name="snpposlist"><a
                                href="?{% url_replace request 'order_by' 'snpposlist' %}">snpposlist</a></th>
                        <th name="listnum"><a
                                href="?{% url_replace request 'order_by' 'listnum' %}">listnum</a>
                        </th>
                        <th name="source"><a
                                href="?{% url_replace request 'order_by' 'source' %}">source</a>
                        </th>

                    </tr>
                    </thead>
                    <tbody>
                    {% autopaginate result %}
                    {% for item in result %}
                        <tr>
                            <td id="tableSelect">
                                <input type="checkbox" name="tableRowCheckBox"
                                       id={{ item.id }} value={{ item.id }}
                                       onclick="stillSelectAll(this);">
                            </td>
                            <td><a href="{% url 'tools:snpView' item.id %}" title="View in graph"
                                   target="_blank">{{ item.id }}</a>
                            </td>
                            <td>{{ item.id1 }}</td>
                            <td>{{ item.strain1 }}</td>
                            <td>{{ item.id2 }}</td>
                            <td>{{ item.strain1 }}</td>
                            <td>{{ item.snpposlist }}</td>
                            <td>{{ item.listnum }}</td>
                            <td>{{ item.source }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="pager">{% paginate %}</div>
            {% else %}
                <p>No results.</p>
            {% endif %}


        </div>

    </div>

{% endblock %}