browse/urls.py
from django.conf.urls import patterns, url
from browse import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
    url(r'^genome/(?P<id>[\w]+)/$', views.genome, name='genome'),
    url(r'^gene/download/$', views.geneDownload, name='geneDownload'),
    url(r'^gene/$', views.geneAll, name='geneAll'),
    url(r'^gene/(?P<id>[\w]+)/$', views.gene, name='gene'),
    url(r'^geneDetail/(?P<id>[\w]+)/$', views.geneDetail, name='geneDetail'),
    url(r'^srna/download/$', views.srnaDownload, name='srnaDownload'),
    url(r'^srna/$', views.srnaAll, name='srnaAll'),
    url(r'^srna/(?P<id>[\w]+)/$', views.srna, name='srna'),
    url(r'^srnaDetail/(?P<id>[\w -:_|%]+)/$', views.srnaDetail, name='srnaDetail'),
    url(r'^exp/download/$', views.expDownload, name='expDownload'),
    url(r'^exp/$', views.expAll, name='expAll'),
    url(r'^exp/(?P<id>[\w]+)/$', views.exp, name='exp'),
    url(r'^expDetail/(?P<id>[\w]+)/$', views.expDetail, name='expDetail'),
)

help/urls.py
from django.conf.urls import patterns, url

from help import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ehfHelp/$',views.ehfHelp,name='ehfHelp'),
    url(r'^searchHelp/$', views.searchHelp, name='searchHelp'),
    url(r'^browseHelp/$', views.browseHelp, name='browseHelp'),
    url(r'^analysisHelp/$', views.analysisHelp, name='analysisHelp'),
    url(r'^restHelp/$', views.restHelp, name='restHelp'),
    url(r'^citeHelp/$', views.citeHelp, name='citeHelp'),
)

search/urls.py
from django.conf.urls import patterns, url
from search import views

urlpatterns = patterns('',
	url(r'^preview/$', views.preview, name='preview'),
    url(r'^quick/$', views.quick, name='quick'),
    url(r'^gene/download/$', views.geneDownload, name='geneDownload'),
    url(r'^srna/download/$', views.srnaDownload, name='srnaDownload'),
    url(r'^exp/download/$', views.expDownload, name='expDownload'),
    url(r'^protein/download/$', views.proteinDownload, name='proteinDownload'),
    url(r'^snp/download/$', views.snpDownload, name='snpDownload'),
    url(r'^correspond/download/$', views.correspondDownload, name='correspondDownload'),
)

smuggler/urls.py
# Copyright (c) 2009 Guilherme Gondim and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.

try:
    from django.conf.urls import url, patterns
except ImportError:  # Django < 1.4
    from django.conf.urls.defaults import url, patterns
                            
from smuggler.views import (dump_data, dump_app_data, dump_model_data,
                            load_data)

dump_data_url = url(
    regex=r'^dump/$',
    view=dump_data,
    name='dump-data'
)

dump_app_data_url = url(
    regex=r'^(?P<app_label>\w+)/dump/$',
    view=dump_app_data,
    name='dump-app-data'
)

dump_model_data_url = url(
    regex=r'^(?P<app_label>\w+)/(?P<model_label>\w+)/dump/$',
    view=dump_model_data,
    name='dump-model-data'
)

load_data_url = url(
    regex=r'^load/$',
    view=load_data,
    name='load-data'
)

urlpatterns = patterns('', dump_model_data_url, dump_app_data_url,
                       dump_data_url, load_data_url)

ypga/urls.py
from django.conf.urls import patterns, include, url
from settings import *
from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ehf.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': MEDIA_ROOT, 'show_indexes': True}),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/images/favicon.ico'}),
    url(r'^$', 'ypga.views.index'),
    url(r'^versionUpdate/$', 'ypga.views.versionUpdate'),

    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^download/', include('download.urls', namespace="download")),
    url(r'^about/', include('about.urls', namespace="about")),
    url(r'^tools/', include('tools.urls', namespace="tools")),
    url(r'^help/', include('help.urls', namespace="help")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from django.utils.encoding import smart_str
from django.db.models import *
import csv

from browse.models import *
from browse.commonVar import *


def queryDb(query, type):
    if type == 'genome':
        q = Q(genomerefno=query) | Q(genometype=query) | Q(gino=query) | Q(uidno=query) | Q(genomename=query) | Q(
            definition__icontains=query) | Q(biovar=query) | Q(strain=query)
        result = Genome.objects.filter(q)

    elif type == 'gene':
        q = Q(id=query) | Q(type=query) | Q(genomerefno=query) | Q(geneid=query) | Q(locus=query) | Q(
            genename=query) | Q(pid=query) | Q(cogno=query) | Q(product=query)
        result = Fragment.objects.filter(q)

    elif type == 'protein':
        q = Q(pid=query) | Q(refseqno=query) | Q(genomerefno=query) | Q(locus=query)
        result = Protein.objects.filter(q)

    else:#exp
        q = Q(locus=query) | Q(genomerefno=query) | Q(genename=query)
        result = ExpressionProfile.objects.filter(q)

    return result

# preview page
def preview(request):
    if request.method == 'GET':
        if 'query' in request.GET:
            query = request.GET['query']
            if query.strip() != '':
                genomeNum = len(queryDb(query, 'genome'))
                geneNum = len(queryDb(query, 'gene'))
                proteinNum = len(queryDb(query, 'protein'))
                expNum = len(queryDb(query, 'exp'))
                total = genomeNum + geneNum + proteinNum + expNum

                return render_to_response('search/preview.html',
                                          {'query': query, 'genomeNum': genomeNum, 'geneNum': geneNum,
                                           'proteinNum': proteinNum, 'expNum': expNum,'total':total},
                                           context_instance=RequestContext(request))

        return HttpResponseRedirect('/')

def geneDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'gene')
                result = result.order_by('locus').values()
            else:
                selected = selected.split(',')
                result = NcbiGene.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=gene.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in geneField:
                rowTitle.append(geneFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in geneField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/')

def srnaDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'srna')
                result = result.order_by('id').values()
            else:
                selected = selected.split(',')
                result = Srna.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=srna.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in srnaField:
                rowTitle.append(srnaFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in srnaField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/')

def expDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'exp')
                result = result.order_by('locus').values()
            else:
                selected = selected.split(',')
                result = ExpressionProfile.objects.filter(locus__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=exp.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in expField:
                rowTitle.append(expFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in expField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/')

def proteinDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'protein')
                result = result.order_by('pid').values()
            else:
                selected = selected.split(',')
                result = NcbiProtein.objects.filter(pid__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=protein.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in proteinField:
                rowTitle.append(proteinFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in proteinField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/')

def snpDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'snp')
                result = result.order_by('id').values()
            else:
                selected = selected.split(',')
                result = Snp.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=snp.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in snpField:
                rowTitle.append(snpFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in snpField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/')

def correspondDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = queryDb(selected,'correspond')
                result = result.order_by('id').values()
            else:
                selected = selected.split(',')
                result = GeneCorrespond.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=correspond.csv'

search/templates/search/correspond.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/search/correspond.js"></script>
    <script src='/static/browse/jquery.fileDownload.js'></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'search:preview' %}">Search</a></li>
            <li class="active">Gene Correspond</li>
        </ol>

        <div class="browseMain">

            <div id="geneSummary">Summary: Query result for "<span id="strain">{{ query }}</span>" contains <span
                    id="interactions">{{ interactions }}</span> entr{{ interactions|pluralize:'y,ies' }}.

            </div>
            <div id="functionDiv" class="functionDiv">
                <div id="selectHint" class="selectHint">
                    <b><span id="selectNumber">0</span></b> items selected
                </div>
                <input type="checkbox" id="selectAllPage" value="selectAllPage" onclick="selectAllPage(this);">
                <label id="selectAllPage"> Select all records </label>

                        <span id="buttonGroup">
                            <button id="downloadFunc" class="btn btn-primary btn-sm"
                                    onclick="performFunction('download');">Download
                            </button>

                        </span>
                        <span id="geneDownloadTip"><a href="{% url 'help:browseHelp' %}#srna" target="_blank"><img
                                src="/static/images/info_20x20.png"></a></span>

            </div>
            <div id="preparing-file-modal" title="Preparing report..." style="display: none;">
                We are preparing your file, please wait...

                <div class="ui-progressbar-value ui-corner-left ui-corner-right"
                     style="width: 100%; height:22px; margin-top: 20px;"></div>
            </div>

            <div id="error-modal" title="Error" style="display: none;">
                There was a problem generating your file, please try again.
            </div>

            {% if result %}
                <table class="table table-hover table-striped table-bordered table-condensed" id="geneTable">
                    <thead>
                    <tr class="tableHead">
                        <th id="tableSelectAll">
                            <input type="checkbox" id="selectCurrentPage" value="selectCurrentPage"
                                   onclick="selectCurrentPage(this)">
                        </th>
                        <th name="id"><a href="?{% url_replace request 'order_by' 'id' %}">ID</a></th>
                        <th name="type"><a href="?{% url_replace request 'order_by' 'type' %}">type</a></th>
                        <th name="coreidentitythreshold"><a
                                href="?{% url_replace request 'order_by' 'coreidentitythreshold' %}">coreidentitythreshold</a>
                        </th>
                        <th name="corecoveragethreshold"><a
                                href="?{% url_replace request 'order_by' 'corecoveragethreshold' %}">corecoveragethreshold</a></th>
                        <th name="source"><a
                                href="?{% url_replace request 'order_by' 'source' %}">source</a>
                        </th>
                        <th name="idcorrespondlist"><a
                                href="?{% url_replace request 'order_by' 'idcorrespondlist' %}">idcorrespondlist</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% autopaginate result %}
                    {% for item in result %}
                        <tr>
                            <td id="tableSelect">
                                <input type="checkbox" name="tableRowCheckBox"
                                       id={{ item.id }} value={{ item.id }}
                                       onclick="stillSelectAll(this);">
                            </td>
                            <td>{{ item.id }}
                            </td>
                            <td>{{ item.type }}</td>
                            <td>{{ item.coreidentitythreshold }}</td>
                            <td>{{ item.corecoveragethreshold }}</td>
                            <td>{{ item.source }}</td>
                            <td>{{ item.idcorrespondlist }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="pager">{% paginate %}</div>
            {% else %}
                <p>No results.</p>
            {% endif %}


        </div>

    </div>

{% endblock %}

search/templates/search/exp.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/search/exp.js"></script>
    <script src='/static/browse/jquery.fileDownload.js'></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'search:preview' %}">Search</a></li>
            <li class="active">Expression Profile</li>
        </ol>

        <div class="browseMain">

            <div id="geneSummary">Summary: Search result for "<span id="strain">{{ query }}</span>" contains <span
                    id="interactions">{{ interactions }}</span> entr{{ interactions|pluralize:'y,ies' }}.

            </div>
            <div id="functionDiv" class="functionDiv">
                <div id="selectHint" class="selectHint">
                    <b><span id="selectNumber">0</span></b> items selected
                </div>
                <input type="checkbox" id="selectAllPage" value="selectAllPage" onclick="selectAllPage(this);">
                <label id="selectAllPage"> Select all records </label>

                        <span id="buttonGroup">
                            <button id="downloadFunc" class="btn btn-primary btn-sm"
                                    onclick="performFunction('download');">Download
                            </button>

                        </span>
                        <span id="geneDownloadTip"><a href="{% url 'help:browseHelp' %}#exp" target="_blank"><img
                                src="/static/images/info_20x20.png"></a></span>

            </div>
            <div id="preparing-file-modal" title="Preparing report..." style="display: none;">
                We are preparing your file, please wait...

                <div class="ui-progressbar-value ui-corner-left ui-corner-right"
                     style="width: 100%; height:22px; margin-top: 20px;"></div>
            </div>

            <div id="error-modal" title="Error" style="display: none;">
                There was a problem generating your file, please try again.
            </div>

            {% if result %}
                <table class="table table-hover table-striped table-bordered table-condensed" id="geneTable">
                    <thead>
                    <tr class="tableHead">
                        <th id="tableSelectAll">
                            <input type="checkbox" id="selectCurrentPage" value="selectCurrentPage"
                                   onclick="selectCurrentPage(this)">
                        </th>
                        <th name="locus"><a href="?{% url_replace request 'order_by' 'locus' %}">locus</a></th>
                        <th name="genename"><a href="?{% url_replace request 'order_by' 'genename' %}">genename</a></th>
                        <th name="classnum"><a href="?{% url_replace request 'order_by' 'classnum' %}">classnum</a>
                        </th>
                        <th name="number_37_vs_26celsius"><a href="?{% url_replace request 'order_by' 'number_37_vs_26celsius' %}">number_37_vs_26celsius</a></th>
                        <th name="cold_shock"><a
                                href="?{% url_replace request 'order_by' 'cold_shock' %}">cold_shock</a>
                        </th>
                        <th name="heat_shock"><a
                                href="?{% url_replace request 'order_by' 'heat_shock' %}">heat_shock</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% autopaginate result %}
                    {% for item in result %}
                        <tr>
                            <td id="tableSelect">
                                <input type="checkbox" name="tableRowCheckBox"
                                       id={{ item.locus }} value={{ item.locus }}
                                       onclick="stillSelectAll(this);">
                            </td>
                            <td>{{ item.locus }}
                            </td>
                            <td>{{ item.genename }}</td>
                            <td>{{ item.classnum }}</td>
                            <td>{{ item.number_37_vs_26celsius }}</td>
                            <td>{{ item.cold_shock }}</td>
                            <td>{{ item.heat_shock }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="pager">{% paginate %}</div>
            {% else %}
                <p>No results.</p>
            {% endif %}


        </div>

    </div>

{% endblock %}

search/templates/search/srna.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/search/srna.js"></script>
    <script src='/static/browse/jquery.fileDownload.js'></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'search:preview' %}">Search</a></li>
            <li class="active">sRNA</li>
        </ol>

        <div class="browseMain">

            <div id="geneSummary">Summary: Query result for "<span id="strain">{{ query }}</span>" contains <span
                    id="interactions">{{ interactions }}</span> entr{{ interactions|pluralize:'y,ies' }}.

            </div>
            <div id="functionDiv" class="functionDiv">
                <div id="selectHint" class="selectHint">
                    <b><span id="selectNumber">0</span></b> items selected
                </div>
                <input type="checkbox" id="selectAllPage" value="selectAllPage" onclick="selectAllPage(this);">
                <label id="selectAllPage"> Select all records </label>

                        <span id="buttonGroup">
                            <button id="downloadFunc" class="btn btn-primary btn-sm"
                                    onclick="performFunction('download');">Download
                            </button>

                        </span>
                        <span id="geneDownloadTip"><a href="{% url 'help:browseHelp' %}#srna" target="_blank"><img
                                src="/static/images/info_20x20.png"></a></span>

            </div>
            <div id="preparing-file-modal" title="Preparing report..." style="display: none;">
                We are preparing your file, please wait...

                <div class="ui-progressbar-value ui-corner-left ui-corner-right"
                     style="width: 100%; height:22px; margin-top: 20px;"></div>
            </div>

            <div id="error-modal" title="Error" style="display: none;">
                There was a problem generating your file, please try again.
            </div>

            {% if result %}
                <table class="table table-hover table-striped table-bordered table-condensed" id="geneTable">
                    <thead>
                    <tr class="tableHead">
                        <th id="tableSelectAll">
                            <input type="checkbox" id="selectCurrentPage" value="selectCurrentPage"
                                   onclick="selectCurrentPage(this)">
                        </th>
                        <th name="id"><a href="?{% url_replace request 'order_by' 'id' %}">ID</a></th>
                        <th name="idsrna"><a href="?{% url_replace request 'order_by' 'idsrna' %}">idsrna</a></th>
                        <th name="name"><a href="?{% url_replace request 'order_by' 'name' %}">Name</a>
                        </th>
                        <th name="type"><a href="?{% url_replace request 'order_by' 'type' %}">Type</a></th>
                        <th name="upstreamgenelocus"><a
                                href="?{% url_replace request 'order_by' 'upstreamgenelocus' %}">upstreamgenelocus</a>
                        </th>
                        <th name="downstreamgenelocus"><a
                                href="?{% url_replace request 'order_by' 'downstreamgenelocus' %}">downstreamgenelocus</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% autopaginate result %}
                    {% for item in result %}
                        <tr>
                            <td id="tableSelect">
                                <input type="checkbox" name="tableRowCheckBox"
                                       id={{ item.id }} value={{ item.id }}
                                       onclick="stillSelectAll(this);">
                            </td>
                            <td>{{ item.id }}
                            </td>
                            <td>{{ item.idsrna }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.type }}</td>
                            <td><a href="{% url 'browse:geneDetail' item.upstreamgenelocus %}" target="_blank">{{ item.upstreamgenelocus }}</a></td>
                            <td><a href="{% url 'browse:geneDetail' item.downstreamgenelocus %}" target="_blank">{{ item.downstreamgenelocus }}</a></td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="pager">{% paginate %}</div>
            {% else %}
                <p>No results.</p>
            {% endif %}


        </div>

    </div>

{% endblock %}