browse/urls.py
from django.conf.urls import patterns, url
from browse import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
    url(r'^genome/(?P<id>[\w]+)/$', views.genome, name='genome'),
    url(r'^gene/download/$', views.geneDownload, name='geneDownload'),
    url(r'^gene/$', views.geneAll, name='geneAll'),
    url(r'^gene/(?P<id>[\w]+)/$', views.gene, name='gene'),
    url(r'^geneDetail/(?P<id>[\w]+)/$', views.geneDetail, name='geneDetail'),
    url(r'^srna/download/$', views.srnaDownload, name='srnaDownload'),
    url(r'^srna/$', views.srnaAll, name='srnaAll'),
    url(r'^srna/(?P<id>[\w]+)/$', views.srna, name='srna'),
    url(r'^srnaDetail/(?P<id>[\w -:_|%]+)/$', views.srnaDetail, name='srnaDetail'),
    url(r'^exp/download/$', views.expDownload, name='expDownload'),
    url(r'^exp/$', views.expAll, name='expAll'),
    url(r'^exp/(?P<id>[\w]+)/$', views.exp, name='exp'),
    url(r'^expDetail/(?P<id>[\w]+)/$', views.expDetail, name='expDetail'),
)

help/urls.py
from django.conf.urls import patterns, url

from help import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ehfHelp/$',views.ehfHelp,name='ehfHelp'),
    url(r'^searchHelp/$', views.searchHelp, name='searchHelp'),
    url(r'^browseHelp/$', views.browseHelp, name='browseHelp'),
    url(r'^analysisHelp/$', views.analysisHelp, name='analysisHelp'),
    url(r'^restHelp/$', views.restHelp, name='restHelp'),
    url(r'^citeHelp/$', views.citeHelp, name='citeHelp'),
)

smuggler/urls.py
# Copyright (c) 2009 Guilherme Gondim and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.

try:
    from django.conf.urls import url, patterns
except ImportError:  # Django < 1.4
    from django.conf.urls.defaults import url, patterns
                            
from smuggler.views import (dump_data, dump_app_data, dump_model_data,
                            load_data)

dump_data_url = url(
    regex=r'^dump/$',
    view=dump_data,
    name='dump-data'
)

dump_app_data_url = url(
    regex=r'^(?P<app_label>\w+)/dump/$',
    view=dump_app_data,
    name='dump-app-data'
)

dump_model_data_url = url(
    regex=r'^(?P<app_label>\w+)/(?P<model_label>\w+)/dump/$',
    view=dump_model_data,
    name='dump-model-data'
)

load_data_url = url(
    regex=r'^load/$',
    view=load_data,
    name='load-data'
)

urlpatterns = patterns('', dump_model_data_url, dump_app_data_url,
                       dump_data_url, load_data_url)

ypga/urls.py
from django.conf.urls import patterns, include, url
from settings import *
from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ehf.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': MEDIA_ROOT, 'show_indexes': True}),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/images/favicon.ico'}),
    url(r'^$', 'ypga.views.index'),
    url(r'^versionUpdate/$', 'ypga.views.versionUpdate'),

    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^download/', include('download.urls', namespace="download")),
    url(r'^about/', include('about.urls', namespace="about")),
    url(r'^tools/', include('tools.urls', namespace="tools")),
    url(r'^help/', include('help.urls', namespace="help")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

browse/views.py
import csv

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import HttpResponseRedirect
from django.http import HttpResponse
from django.utils.encoding import smart_str
from django.db.models import Q

from browse.models import *
from commonVar import *
from ypga.settings import GENOME_DIR


# Create your views here.

#the welcome page
def index(request):
    return render_to_response('browse/index.html', context_instance=RequestContext(request))


def genome(request, id):
    result = Genome.objects.filter(strain=id).order_by('genometype')
    publicationDict = {}
    for item in result:
        pubList = item.reference.split(';')
        pubList = list(set(pubList))
        if '' in pubList:
            pubList.remove('')
        publicationDict[item.genomerefno] = pubList

    return render_to_response('browse/genome.html',
                              {'result': result, 'strain': id, 'publicationDict': publicationDict,
                               'GENOME_DIR': GENOME_DIR},
                              context_instance=RequestContext(request))


def gene(request, id):
    result = Fragment.objects.filter(strain=id).order_by('locus')
    if (len(result)):
        #sort the column
        order = request.GET.get('order_by', 'locus')
        result = result.order_by(order)

    aaList = []
    for item in result:
        if item.locus not in aaList:
            aaList.append(item.locus)
    geneNumber = len(aaList)
    interactions = len(result)

    return render_to_response('browse/gene.html',
                              {'result': result, 'strain': id, 'geneNumber': geneNumber, 'interactions': interactions},
                              context_instance=RequestContext(request))


def geneAll(request):
    result = Fragment.objects.all().order_by('locus')

    tmp = Fragment.objects.all().values_list('strain')
    id = []
    for item in tmp:
        if item[0] not in id:
            id.append(item[0])

    if (len(result)):
        #sort the column
        order = request.GET.get('order_by', 'locus')
        result = result.order_by(order)

    geneNumber = len(result.values_list('locus').distinct())
    interactions = len(result)

    return render_to_response('browse/gene.html',
                              {'result': result, 'strain': ','.join(id), 'geneNumber': geneNumber,
                               'interactions': interactions},
                              context_instance=RequestContext(request))


def geneDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                result = Fragment.objects.filter(strain=selected).order_by('locus').values()
            else:
                selected = selected.split(',')
                result = Fragment.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=gene.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in geneField:
                rowTitle.append(geneFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in geneField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/browse')


def geneDetail(request, id):
    geneResult = Fragment.objects.filter(locus=id)
    for item in geneResult:
        genomerefno = item.genomerefno  #may have two for 91001 locus

    genomeResult = Genome.objects.filter(genomerefno=genomerefno)

    publicationDict = {}
    for item in genomeResult:
        pubList = item.reference.split(';')
        pubList = list(set(pubList))
        if '' in pubList:
            pubList.remove('')
        publicationDict[item.genomerefno] = pubList

    proteinResult = Protein.objects.filter(locus=id)  #may have two for 91001 locus

    reannoResult = Reanno.objects.filter(id_original=id)

    expResult = ExpressionProfile.objects.filter(locus=id)

    return render_to_response('browse/geneDetail.html', {
        'geneResult': geneResult,
        'genomeResult': genomeResult,
        'publicationDict': publicationDict,
        'proteinResult': proteinResult,
        'reannoResult': reannoResult,
        'expResult': expResult,
        'id': id,
    },context_instance=RequestContext(request))


def srnaDetail(request, id):
    srnaResult = Srna.objects.filter(id=id)
    return render_to_response('browse/srnaDetail.html', {
        'srnaResult': srnaResult, 'id': id}, context_instance=RequestContext(request))


def srna(request, id):
    #change columns?
    if 'columns' in request.GET:
        selectedColumns_tmp = request.GET['columns']
        selectedColumns = selectedColumns_tmp.split(',')
        request.session['has_changed_srna'] = True  # set the session, not change
        request.session['srnaColumns'] = selectedColumns  #store the columns

    if 'has_changed_srna' not in request.session:
        defaultColumns = ['id', 'idsrna', 'name', 'type', 'upstreamgenelocus', 'downstreamgenelocus']
        request.session['srnaColumns'] = defaultColumns  #store the columns

    genomeRes = Genome.objects.filter(strain=id).values_list('genomerefno')
    refList = []
    for item in genomeRes:
        refList.append(item[0])

    #columns to display start!

    displayColumns = request.session['srnaColumns']
    if displayColumns == '':
        displayColumns = ['id', 'idsrna', 'name', 'type', 'upstreamgenelocus', 'downstreamgenelocus']
    displayColumnsDic = []
    for item in displayColumns:
        displayColumnsDic.append([item, srnaFieldDic[item]])
    #columns to display end

    result = Srna.objects.filter(genomerefno__in=refList).order_by('id')
    if (len(result)):
        #sort the column
        order = request.GET.get('order_by', 'id')
        result = result.order_by(order)

    interactions = len(result)

    #custom display columns start!
    columns = []
    for i in range(0, len(srnaField), 1):
        columns.append([srnaField[i], srnaFieldDic[srnaField[i]]])
    #custom display columns end

    print columns

    return render_to_response('browse/srna.html',
                              {'result': result, 'strain': id, 'interactions': interactions, 'columns': columns,
                               'displayColumnsDic': displayColumnsDic},
                              context_instance=RequestContext(request))


def srnaAll(request):
    result = Srna.objects.all().order_by('id')
    tmp = result.values_list('strain')
    id = []
    for item in tmp:
        if item[0] not in id:
            id.append(item[0])

    if (len(result)):
        #sort the column
        order = request.GET.get('order_by', 'id')
        result = result.order_by(order)

    interactions = len(result)

    return render_to_response('browse/srna.html',
                              {'result': result, 'strain': ','.join(id), 'interactions': interactions},
                              context_instance=RequestContext(request))


def srnaDownload(request):
    if request.method == 'GET':
        if 'type' in request.GET and 'selected' in request.GET:
            type = request.GET['type']
            selected = request.GET['selected']
            if type == 'all':
                selected = selected.split(',')
                genomeRes = Genome.objects.filter(strain__in=selected).values_list('genomerefno')
                refList = []
                for item in genomeRes:
                    refList.append(item[0])
                result = Srna.objects.filter(genomerefno__in=refList).order_by('id').values()
            else:
                selected = selected.split(',')
                result = Srna.objects.filter(id__in=selected).values()

            response = HttpResponse(content_type="text/csv")
            response.write('\xEF\xBB\xBF')
            response['Content-Disposition'] = 'attachment; filename=srna.csv'
            writer = csv.writer(response)

            # store row title description
            rowTitle = []
            for item in srnaField:
                rowTitle.append(srnaFieldDic[item])
            writer.writerow(rowTitle)

            #get data from database
            #data = allEHFPI.objects.values()
            for item in result:
                res = []
                for i in srnaField:
                    # if type(item[i]) is types.UnicodeType:
                    #     res.append(item[i].encode('utf-8'))
                    # else:   #long type
                    #     res.append(item[i])
                    res.append(smart_str(item[i]))
                writer.writerow(res)
            return response

    return HttpResponseRedirect('/browse')


def exp(request, id):
    #change columns?
    if 'columns' in request.GET:
        selectedColumns_tmp = request.GET['columns']
        selectedColumns = selectedColumns_tmp.split(',')
        request.session['has_changed_exp'] = True  # set the session, not change
        request.session['expColumns'] = selectedColumns  #store the columns

    if 'has_changed_exp' not in request.session:
        defaultColumns = ['locus', 'genename', 'classnum', 'number_37_vs_26celsius', 'cold_shock', 'heat_shock']
        request.session['expColumns'] = defaultColumns  #store the columns

browse/templates/browse/gene.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/browse/gene.js"></script>
    <script src='/static/browse/jquery.fileDownload.js'></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'browse:index' %}">Browse</a></li>
            <li class="active">Gene</li>
        </ol>

        <div class="browseMain">

            <div id="geneSummary">Summary: Strain <span id="strain">{{ strain }}</span> contains <span
                    id="geneNumber">{{ geneNumber }}</span> gene{{ geneNumber|pluralize }}, <span
                    id="interactions">{{ interactions }}</span> entr{{ interactions|pluralize:'y,ies' }}.

            </div>
            <div id="functionDiv" class="functionDiv">
                <div id="selectHint" class="selectHint">
                    <b><span id="selectNumber">0</span></b> items selected
                </div>
                <input type="checkbox" id="selectAllPage" value="selectAllPage" onclick="selectAllPage(this);">
                <label id="selectAllPage"> Select all records </label>

                        <span id="buttonGroup">
                            <button id="downloadFunc" class="btn btn-primary btn-sm"
                                    onclick="performFunction('download');">Download
                            </button>

                        </span>
                        <span id="geneDownloadTip"><a href="{% url 'help:browseHelp' %}#gene" target="_blank"><img
                                src="/static/images/info_20x20.png"></a></span>

            </div>
            <div id="preparing-file-modal" title="Preparing report..." style="display: none;">
                We are preparing your file, please wait...

                <div class="ui-progressbar-value ui-corner-left ui-corner-right"
                     style="width: 100%; height:22px; margin-top: 20px;"></div>
            </div>

            <div id="error-modal" title="Error" style="display: none;">
                There was a problem generating your file, please try again.
            </div>

            {% if result %}
                <table class="table table-hover table-striped table-bordered table-condensed" id="geneTable">
                    <thead>
                    <tr class="tableHead">
                        <th id="tableSelectAll">
                            <input type="checkbox" id="selectCurrentPage" value="selectCurrentPage"
                                   onclick="selectCurrentPage(this)">
                        </th>
                        <th name="locus"><a href="?{% url_replace request 'order_by' 'locus' %}">Locus</a></th>
                        <th name="genomerefno"><a href="?{% url_replace request 'order_by' 'genomerefno' %}">genome Ref
                            no</a></th>
                        <th name="genename"><a href="?{% url_replace request 'order_by' 'genename' %}">Gene Name</a>
                        </th>
                        <th name="type"><a href="?{% url_replace request 'order_by' 'type' %}">Genome Type</a></th>
                        <th name="product"><a href="?{% url_replace request 'order_by' 'product' %}">Product</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% autopaginate result %}
                    {% for item in result %}
                        <tr>
                            <td id="tableSelect">
                                <input type="checkbox" name="tableRowCheckBox"
                                       id={{ item.id }} value={{ item.id }}
                                       onclick="stillSelectAll(this);">
                            </td>
                            <td><a href="/browse/geneDetail/{{ item.locus }}">{{ item.locus }}</a>
                            </td>
                            <td>{{ item.genomerefno }}</td>
                            <td>{{ item.genomename }}</td>
                            <td>{{ item.type }}</td>
                            <td>{{ item.product }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div id="pager">{% paginate %}</div>
            {% else %}
                <p>No results.</p>
            {% endif %}


        </div>

    </div>

{% endblock %}

browse/templates/browse/genome.html
{% extends "base.html" %}
{% load pagination_tags %}


{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    {% load getDict %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/browse/browse.js"></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li><a href="{% url 'browse:index' %}">Browse</a></li>
            <li class="active">Genome</li>
        </ol>

        <div class="browseMain">
            <p id="strain">Strain {{ strain }}</p>
            <table class="table table-hover table-striped table-bordered table-condensed">
                <thead>
                <tr class="tableHead">
                    <th>NCBI ref no</th>
                    <th>Type</th>
                    <th>Genome Name</th>
                    <th>Length(bp)</th>
                    <th>Gene Number</th>
                </tr>
                </thead>
                <tbody>
                {% for item in result %}
                    <tr>
                        <td><a href="/browse/genome/{{ strain }}#{{ item.genomerefno }}">{{ item.genomerefno }}</a></td>
                        <td>{{ item.genometype }}</td>
                        <td>{{ item.genomename }}</td>
                        <td>{{ item.length }}</td>
                        <td>{{ item.genenum }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>


            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-toggle="collapse" data-parent="#accordion"
                               href="#collapseOne">
                                <b>Chromosome Details</b>
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            {% for item in result %}
                                <div class="genomeDetail" id="{{ item.genomerefno }}">
                                    <div id="title">#{{ forloop.counter }}: {{ item.genomerefno }}</div>
                                    <label>genomeRefNo:</label>

                                    <span id="genenmeDetail">{{ item.genomerefno }}</span> <br/>
                                    <label>genomeType:</label>

                                    <span id="genenmeDetail">{{ item.genometype }}</span> <br/>
                                    <label>geneNum:</label>

                                    <span id="genenmeDetail">{{ item.genenum }}</span> <br/>
                                    <label>giNo:</label>

                                    <span id="genenmeDetail">{{ item.gino }}</span> <br/>
                                    <label>uidNo:</label>

                                    <span id="genenmeDetail">{{ item.uidno }}</span> <br/>
                                    <label>genomeName:</label>

                                    <span id="genenmeDetail">{{ item.genomename }}</span> <br/>
                                    <label>definition:</label>

                                    <span id="genenmeDetail">{{ item.definition }}</span> <br/>
                                    <label>seq:</label>

                                    <span id="genenmeDetail"><a href="{{ GENOME_DIR }}\{{ item.genomerefno }}.fasta">{{ item.genomerefno }}.fasta </a></span> <br/>
                                    <label>length:</label>

                                    <span id="genenmeDetail">{{ item.length }}</span> <br/>
                                    <label>source:</label>

                                    <span id="genenmeDetail">{{ item.source }}</span> <br/>
                                    <label>type:</label>

                                    <span id="genenmeDetail">{{ item.type }}</span> <br/>
                                    <label>biovar:</label>

                                    <span id="genenmeDetail">{{ item.biovar }}</span> <br/>
                                    <label>strain:</label>

                                    <span id="genenmeDetail">{{ item.strain }}</span> <br/>
                                    <label>updateTime:</label>

                                    <span id="genenmeDetail">{{ item.updatetime }}</span> <br/>

                                    <div class="panel-group" id="accordion{{ forloop.counter }}">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a data-toggle="collapse" data-toggle="collapse"
                                                       data-parent="#accordion{{ forloop.counter }}"
                                                       href="#collapse{{ forloop.counter }}">
                                                        <b>Reference</b>
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                                                <div class="panel-body">
                                                    <label>reference:</label><br/>
                                                    {% for ref in publicationDict|get:item.genomerefno %}
                                                        {{ forloop.counter }}. <span id="genenmeDetail">{{ ref }}</span>
                                                        <br/>
                                                        <br/>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="gotop">
            <a href="#" title="Back to the top of the page"><span
                    class="glyphicon glyphicon-circle-arrow-up"></span>
                Top</a>
        </div>

    </div>

{% endblock %}

browse/templates/browse/index.html
{% extends "base.html" %}
{% load pagination_tags %}


{% block title %}
    <title>TODYP - Browse</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    {% load tableSort %}
    <link rel="stylesheet" type="text/css" href="{% static 'browse/browse.css' %}"/>
    <script src="/static/browse/browse.js"></script>

    <div class="main">

        <ol class="breadcrumb">
            <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
            <li class="active">Browse</li>
        </ol>

        <div class="browseMain">
            <div class="browseTitle">
                Genome Data
            </div>
            <hr/>
            <div class="browseContent">
                <p>genome data for all strains</p>
                <div>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'CO92' %}" role="button">CO92</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' '91001' %}" role="button">91001</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'Nepal516' %}"
                       role="button">Nepal516</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'Angola' %}" role="button">Angola</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'Antiqua' %}"
                       role="button">Antiqua</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'KIM' %}" role="button">KIM</a>
                </div>
                <div>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'PestoidesF' %}" role="button">Pestoides F</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'A1122' %}" role="button">A1122</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'Harbin35' %}"
                       role="button">Harbin35</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'D106004' %}"
                       role="button">D106004</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'D182038' %}"
                       role="button">D182038</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:genome' 'Z176003' %}"
                       role="button">Z176003</a>
                </div>
            </div>

            <div class="browseTitle">
                <a href="/browse/gene/">Gene Data</a>
            </div>
            <hr/>
            <div class="browseContent">
                <p>gene data for all strains</p>
                <div>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'CO92' %}" role="button">CO92</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' '91001' %}" role="button">91001</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'Nepal516' %}"
                       role="button">Nepal516</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'Angola' %}" role="button">Angola</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'Antiqua' %}"
                       role="button">Antiqua</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'KIM' %}" role="button">KIM</a>
                </div>
                <div>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'PestoidesF' %}" role="button">Pestoides F</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'A1122' %}" role="button">A1122</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'Harbin35' %}"
                       role="button">Harbin35</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'D106004' %}"
                       role="button">D106004</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'D182038' %}"
                       role="button">D182038</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:gene' 'Z176003' %}"
                       role="button">Z176003</a>
                </div>
            </div>

            <div class="browseTitle">
                <a href="/browse/srna/">sRNA Data</a>
            </div>
            <hr/>
            <div class="browseContent">
                <p>sRNA data for all strains</p>
                <div>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:srna' '91001' %}" role="button">91001</a>
                    <a class="btn btn-success btn-sm" href="{% url 'browse:srna' 'KIM' %}" role="button">KIM</a>
                </div>

            </div>

            <div class="browseTitle">
                <a href="/browse/exp/">Expression Profile Data</a>
            </div>
            <hr/>
            <div class="browseContent">
                <p>expression profile data for all strains</p>
                <div>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:exp' '91001' %}" role="button">91001</a>
                    <a class="btn btn-info btn-sm" href="{% url 'browse:exp' 'CO92' %}" role="button">CO92</a>
                </div>

            </div>

        </div>

    </div>

{% endblock %}