about/urls.py
from django.conf.urls import patterns, url
from about import views

urlpatterns = patterns('',
    url(r'^statistics/$', views.statistics, name='statistics'),
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^copyright/$', views.copyright, name='copyright'),
    url(r'^externalLinks/$', views.external, name='external'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^lab/$', views.lab, name='lab'),
)

help/urls.py
from django.conf.urls import patterns, url

from help import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ehfHelp/$',views.ehfHelp,name='ehfHelp'),
    url(r'^searchHelp/$', views.searchHelp, name='searchHelp'),
    url(r'^browseHelp/$', views.browseHelp, name='browseHelp'),
    url(r'^analysisHelp/$', views.analysisHelp, name='analysisHelp'),
    url(r'^restHelp/$', views.restHelp, name='restHelp'),
    url(r'^citeHelp/$', views.citeHelp, name='citeHelp'),
)

smuggler/urls.py
# Copyright (c) 2009 Guilherme Gondim and contributors
#
# This file is part of Django Smuggler.
#
# Django Smuggler is free software under terms of the GNU Lesser
# General Public License version 3 (LGPLv3) as published by the Free
# Software Foundation. See the file README for copying conditions.

try:
    from django.conf.urls import url, patterns
except ImportError:  # Django < 1.4
    from django.conf.urls.defaults import url, patterns
                            
from smuggler.views import (dump_data, dump_app_data, dump_model_data,
                            load_data)

dump_data_url = url(
    regex=r'^dump/$',
    view=dump_data,
    name='dump-data'
)

dump_app_data_url = url(
    regex=r'^(?P<app_label>\w+)/dump/$',
    view=dump_app_data,
    name='dump-app-data'
)

dump_model_data_url = url(
    regex=r'^(?P<app_label>\w+)/(?P<model_label>\w+)/dump/$',
    view=dump_model_data,
    name='dump-model-data'
)

load_data_url = url(
    regex=r'^load/$',
    view=load_data,
    name='load-data'
)

urlpatterns = patterns('', dump_model_data_url, dump_app_data_url,
                       dump_data_url, load_data_url)

ypga/urls.py
from django.conf.urls import patterns, include, url
from settings import *
from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ehf.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': MEDIA_ROOT, 'show_indexes': True}),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/images/favicon.ico'}),
    url(r'^$', 'ypga.views.index'),
    url(r'^versionUpdate/$', 'ypga.views.versionUpdate'),

    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^browse/', include('browse.urls', namespace="browse")),
    url(r'^download/', include('download.urls', namespace="download")),
    url(r'^about/', include('about.urls', namespace="about")),
    url(r'^tools/', include('tools.urls', namespace="tools")),
    url(r'^help/', include('help.urls', namespace="help")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

about/models.py
from django.db import models

# the model for sumbit form
class submitModel(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50)
    institute = models.CharField(max_length=200)
    content = models.TextField()
    time = models.DateTimeField(auto_now=True, auto_now_add=True)

    class Meta:
        unique_together = (("name", "email","institute"),)

# the model for contact form
class contactModel(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    email = models.EmailField()
    time = models.DateTimeField(auto_now=True, auto_now_add=True)

class staticticsModel(models.Model):
    tableName = models.CharField(max_length=255)
    itemNumber = models.IntegerField()
    source = models.CharField(max_length=255)
    notes = models.CharField(max_length=255)

about/forms.py
from about.models import submitModel,contactModel
from django.forms import ModelForm,Textarea
from django.forms import TextInput

class submitForm(ModelForm):
    class Meta:
        model = submitModel
        widgets = {
            'content': Textarea(attrs={'cols': 100, 'rows': 8}),
        }

        error_messages = {
            'email': {
                'required':'email is required',
                'invalid': 'please input a valid email address'
            },
            'name':{
                'required':"name is required",
            },
            'institute':{
                'required':"institute is required",
            },
            'content':{
                'required': "content is required",
            }
        }

class contactForm(ModelForm):
    class Meta:
        model = contactModel
        widgets = {
            'content': Textarea(attrs={'cols': 100, 'rows': 8}),
        }
        error_messages = {
            'email': {
                'required':'email is required',
                'invalid': 'please input a valid email address'
            },
            'title':{
                'required':"title is required",
            },
            'content':{
                'required': "content is required",
            }
        }

about/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.shortcuts import HttpResponseRedirect
from django.template import RequestContext
from forms import *
from models import staticticsModel

# Create your views here.
def index(request):
    return render_to_response('about/index.html')

def statistics(request):
    result = staticticsModel.objects.all()
    return render_to_response('about/statistics.html',{'result':result})

def submit(request):
    # AuthorFormSet = modelformset_factory(Author)  we can use factory, but this time we still use ModelForm
    myForm = submitForm()
    if request.method == 'POST':
        myForm = submitForm(request.POST)
        if myForm.is_valid():
            myForm.save()
            return HttpResponseRedirect('/about/submitHistory')

    return render_to_response('about/submit.html',locals(),context_instance=RequestContext(request))

def contact(request):
    myForm = contactForm()
    if request.method == 'POST':
        myForm = contactForm(request.POST)
        if myForm.is_valid():
            myForm.save()
            # send a mail to administrator
            # get administrator email from settings.py
            # title = myForm.cleaned_data['title']
            # email = myForm.cleaned_data['email']
            # content = myForm.cleaned_data['content']
            # send_mail(title, content, email, [ADMIN_EMAIL], fail_silently=True)
            return HttpResponseRedirect('/about/thanks/')

    return render_to_response('about/contact.html',locals(),context_instance=RequestContext(request))

def copyright(request):
    return render_to_response('about/copyright.html')

def external(request):
    return render_to_response('about/external.html')

def thanks(request):
    return render_to_response('about/thanks.html')

def lab(request):
    return render_to_response('about/lab.html')

about/templates/about/contact.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>

    <div class="main">
        <div class="contact">

            <ol class="breadcrumb">
                <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">Contact</li>
            </ol>

            <div class="contactContent">
                <p>you can contact us in three ways</p>

                <div class="panel panel-primary">
                    <!-- Default panel contents -->
                    <!-- List group -->
                    <ul class="list-group">
                        <li class="list-group-item">
                            <form method="post" class="form-horizontal" role="form"
                                  action="{% url 'about:contact' %}">{% csrf_token %}

                                <div class="fieldWrapper">
                                    <label for="id_title">Title*:</label><br/>
                                    {{ myForm.title.errors }}
                                    {{ myForm.title }}<span id="hint">(question)</span>
                                </div>

                                <div class="fieldWrapper">
                                    <label for="id_content">Content*:</label><br/>
                                    {{ myForm.content.errors }}
                                    {{ myForm.content }}
                                </div>

                                <div class="fieldWrapper">
                                    <label for="id_email">Email*:</label><br/>
                                    {{ myForm.email.errors }}
                                    {{ myForm.email }}<span id="hint">(example@example.com)</span>
                                </div>

                                <input type="submit" value="Submit">
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="panel panel-primary">
                    <!-- Default panel contents -->
                    <!-- List group -->
                    <ul class="list-group">
                        <li class="list-group-item">You can send mail to<br/>
                            <b>YiQing Mao</b> (<a href="mailto:polo_simon@sina.com">polo_simon@sina.com</a>)<br/>
                            Institute Of Microbiology And Epidemiology<br/>
                            Academy of Military Medical Sciences<br/>
                            Beijing, China<br/>
                            </li>
                    </ul>
                </div>
                <div class="panel panel-primary">
                    <!-- Default panel contents -->
                    <!-- List group -->
                    <ul class="list-group">
                        <li class="list-group-item">You can also join our mailing list at <a href="https://groups.google.com/d/forum/todyp" target="_blank">todyp@googlegroups.com</a>.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

about/templates/about/copyright.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>
    <div class="main">
        <div class="copyright">

            <ol class="breadcrumb">
                <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">Copyright</li>
            </ol>

            <div class="copyrightTitle">
                Copyright
            </div>
            <div class="copyrightContent">
                TODYP is licensed under a Creative Commons Attribution 3.0 Unported License. This means that you are
                free to copy,
                distribute, display and make commercial use of all records from the TODYP database provided appropriate
                credit is given.
            </div>
            <div class="copyrightTitle">
                Acknowledgement
            </div>
            <div class="copyrightContent">
                The database acknowledges several open-source projects:<br/>
                <a href="https://www.djangoproject.com/">Django</a><br/>
                <a href="http://getbootstrap.com/">Bootstrap</a><br/>


                Database data are curated by <a href="mailto:maoyq@bmi.ac.cn">YiQing Mao</a>. <br/>
                Website design by <a href="mailto:liuyang@bmi.ac.cn">Yang Liu</a>. <br/>
                You can find the project source code at sourceForge.
            </div>
        </div>
    </div>
{% endblock %}

about/templates/about/external.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>
    <div class="main">
        <div class="external">
            <ol class="breadcrumb">
                <li><a href={% url 'ypga.views.index' %}>Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">externalLinks</li>
            </ol>
            <div class="externalContent">
                More useful tools and database resources:
                <ol>
                    <li><b>DEG</b> <a href="http://tubic.tju.edu.cn/deg/">http://tubic.tju.edu.cn/deg</a></li>
                    <li><b>PHI-base</b> <a href="http://www.phi-base.org/">http://www.phi-base.org</a></li>
                    <li><b>GenomeRNAi</b> <a href="http://www.genomernai.org/">http://www.genomernai.org</a></li>
                </ol>
            </div>
        </div>
    </div>
{% endblock %}

about/templates/about/index.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>

    <div class="main">
        <div class="aboutIndex">
            <ol class="breadcrumb">
                <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
                <li class="active">About</li>
            </ol>

            <div class="AboutItem">
                <div class="AboutTitle">
                    <a href= {% url 'about:statistics' %}>Statistics</a>
                </div>
                <div class="AboutContent">
                    This is a brief statistics of the data in EHFPI database.
                </div>
            </div>


            <div class="AboutItem">
                <div class="AboutTitle">
                    <a href= {% url 'about:submit' %}>Submit</a>
                </div>
                <div class="AboutContent">
                    Users can provide literature information to our websites. What's more, we provide a excel
                    templates which can be used to submit detail data to EHFPI database.
                </div>
            </div>

            <div class="AboutItem">
                <div class="AboutTitle">
                    <a href= {% url 'about:copyright' %}>Copyright</a>
                </div>
                <div class="AboutContent">
                    The copyright information and acknowledgement.
                </div>
            </div>

            <div class="AboutItem">
                <div class="AboutTitle">
                    <a href= {% url 'about:external' %}>External Links</a>
                </div>
                <div class="AboutContent">
                    Useful links that may be helpful for your research.
                </div>
            </div>

            <div class="AboutItem">
                <div class="AboutTitle">
                    <a href= {% url 'about:lab' %}>Our Lab</a>
                </div>
                <div class="AboutContent">
                    An introduction of LAM lab.
                </div>
            </div>

        </div>
    </div>
{% endblock %}

about/templates/about/lab.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>
    <div class="main">
        <div class="external">
            <ol class="breadcrumb">
                <li><a href={% url 'ypga.views.index' %}>Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">Lab Introduction</li>
            </ol>
            <div class="labContent">
                A brief introduction of LAM.
                <div class="labTitle">Faculties and Students</div>
                <div class="labContent">
                    <div class="row">
                        <div id="image" class="col-md-2">
                            <img src="/static/about/image/1.jpg" width="100" height="100">
                        </div>
                        <div id="intro" class="col-md-8">
                            Yiqing Mao, Phd students, major in bioinformatics.
                        </div>
                    </div>
                </div>
                <div class="labTitle">Publications</div>
                <div class="labContent"></div>

            </div>
        </div>
    </div>
{% endblock %}

about/templates/about/statistics.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>

    <div class="main">
        <div class="statistics">

            <ol class="breadcrumb">
                <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">Statistics</li>
            </ol>

            <div class="statisticsIntro">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Overview of TODYP data.
            </div>

            <div class="statisticsMap">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr class="success">
                        <th>Table name</th>
                        <th>Item number</th>
                        <th>Source</th>
                        <th>Notes</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in result %}
                        <tr>
                            <td>{{ item.tableName }}</td>
                            <td>{{ item.itemNumber }}</td>
                            <td>{{ item.source }}</td>
                            <td>{{ item.notes }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>


    </div>
{% endblock %}

about/templates/about/submit.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>

    <div class="main">
        <div class="submitAbout">
            <ol class="breadcrumb">
                <li><a href="{% url 'ypga.views.index' %}">Home</a></li>
                <li><a href="{% url 'about:index' %}">About</a></li>
                <li class="active">Submit</li>
            </ol>

            <div class="submitTitle">
                Has new TODYP data been published?
            </div>
            <div class="submitContent">
                <div class="message">
                    <ul>

                        <li>You can fill in the form below to notify us (e.g., title, pubmed ID).</li>
                    </ul>

                </div>
                <div class="submitForm">
                    <form method="post" class="form-horizontal" role="form"
                          action="{% url 'about:submit' %}">{% csrf_token %}

                        <div class="fieldWrapper">
                            <label for="id_email">Email*:</label><br/>
                            {{ myForm.email.errors }}
                            {{ myForm.email }}<span id="hint">(example@example.com)</span>
                        </div>

                        <div class="fieldWrapper">
                            <label for="id_name">Name*:</label><br/>
                            {{ myForm.name.errors }}
                            {{ myForm.name }}<span id="hint">(John)</span>
                        </div>

                        <div class="fieldWrapper">
                            <label for="id_institute">Institute*:</label><br/>
                            {{ myForm.institute.errors }}
                            {{ myForm.institute }}<span id="hint">(Academy of Military Medical Sciences)</span>
                        </div>

                        <div class="fieldWrapper">
                            <label for="id_content">Content*:</label><br/>
                            {{ myForm.content.errors }}
                            {{ myForm.content }}
                        </div>

                        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
                    </form>
                </div>

            </div>
            <div class="submitTitle">
                Any other questions？
            </div>
            <div class="submitContent">
                Feel free to <a href= {% url 'about:contact' %}>contact us</a> if you have any other questions.
            </div>
        </div>
    </div>
{% endblock %}

about/templates/about/thanks.html
{% extends "base.html" %}
{% block title %}
    <title>TODYP - About</title>
{% endblock %}

{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"/>
<div class = "main">
    <div class = "thanks">
        Thanks, we will reply to you as soon as possible.<br/>
        <img src="/static/about/thanks.gif">
    </div>
</div>
{% endblock %}